version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: petflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: petflow-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: